### ISSUE TITLE
nil pointer when build

### ISSUE THREAD

**Issue by Mushus** [oxequa/realize#198]
This error occurred When I build my source code.
```
Watching 39 file/s 15 folder/s
Install started
Install completed in 4.314 s
Running..
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a553e]

goroutine 129 [running]:
os.(*Process).signal(0x0, 0x96e360, 0xb72630, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:56 +0x2e
os.(*Process).Signal(0x0, 0x96e360, 0xb72630, 0x4, 0xc420050b88)
        /usr/local/go/src/os/exec.go:129 +0x3f
github.com/oxequa/realize/realize.(*Project).run.func1(0xc420050c80)
        /go/src/github.com/oxequa/realize/realize/projects.go:575 +0x5c
github.com/oxequa/realize/realize.(*Project).run(0xc420080a00, 0xc4201fd960, 0x7, 0xc42025f440, 0xc420028540, 0x96b420, 0xc420158f00)
        /go/src/github.com/oxequa/realize/realize/projects.go:638 +0xb6b
github.com/oxequa/realize/realize.(*Project).Reload.func3(0xc420080a00, 0xc42025f440, 0xc420028540)
        /go/src/github.com/oxequa/realize/realize/projects.go:263 +0x16b
created by github.com/oxequa/realize/realize.(*Project).Reload
        /go/src/github.com/oxequa/realize/realize/projects.go:261 +0x2d0
```

It seems to occurred this error when realize could not build.Start
https://github.com/oxequa/realize/blob/master/realize/projects.go#L575
https://github.com/oxequa/realize/blob/master/realize/projects.go#L638

**Comment by Mushus** [comment]
The cause of this problem is below: 
.realize.yaml
```
schema:
  path: .
```
