### ISSUE TITLE
unknown segmentation violation

### ISSUE THREAD

**Issue by dooglegh** [oxequa/realize#224]
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4588fc]

goroutine 3120 [running]:
fmt.(*buffer).WriteString(...)
        /usr/local/go/src/fmt/print.go:82
fmt.(*fmt).padString(0xc4201b81c0, 0x0, 0x29)
        /usr/local/go/src/fmt/format.go:110 +0x9c
fmt.(*fmt).fmt_s(0xc4201b81c0, 0x0, 0x29)
        /usr/local/go/src/fmt/format.go:328 +0x61
fmt.(*pp).fmtString(0xc4201b8180, 0x0, 0x29, 0x76)
        /usr/local/go/src/fmt/print.go:437 +0x11f
fmt.(*pp).printArg(0xc4201b8180, 0x85ed00, 0xc420407ad0, 0x76)
        /usr/local/go/src/fmt/print.go:671 +0x789
fmt.(*pp).doPrint(0xc4201b8180, 0xc4201fbd48, 0x1, 0x1)
        /usr/local/go/src/fmt/print.go:1134 +0x67
fmt.Sprint(0xc4201fbd48, 0x1, 0x1, 0xc42018f420, 0xd54ff0)
        /usr/local/go/src/fmt/print.go:239 +0x52
github.com/fatih/color.(*Color).Sprint(0xc42018f420, 0xc4201fbd48, 0x1, 0x1, 0x85ed00, 0x1)
        /home/doogle/go/src/github.com/fatih/color/color.go:256 +0x3f
github.com/oxequa/realize/realize.colorBase.Regular(0x5e, 0xc4201fbd48, 0x1, 0x1, 0xc420b268a0, 0x26)
        /home/doogle/go/src/github.com/oxequa/realize/realize/style.go:27 +0x80
github.com/oxequa/realize/realize.(*Project).Reload.func2(0xc42002c5a0, 0xc42044e1e0, 0xc4200a3100)
        /home/doogle/go/src/github.com/oxequa/realize/realize/projects.go:253 +0x237
created by github.com/oxequa/realize/realize.(*Project).Reload
        /home/doogle/go/src/github.com/oxequa/realize/realize/projects.go:241 +0x291`

**Comment by Asoseil** [comment]
thanks for the support and for the reports, in the last months we had some company changes but in the first trimester 2019 we will release a new version
